
services:
  gitea:
    build:
      context: .
      args:
        USER_UID: 1000
        USER_GID: 1000
    ports:
      - "3000:3000"
      - "2222:22"
    environment:
      - USER=git
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - git-data:/data

volumes:
  git-data:
